name: Build

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  terragrunt:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v2.0.0
        with:
          args: pack .\terragrunt\terragrunt.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v2.0.0
        with:
          args: install -source . -force --force-dependencies terragrunt

      - name: Terragrunt & Terraform Version
        run: |
          terragrunt -version
          terraform -version

      - name: Choco uninstall
        uses: crazy-max/ghaction-chocolatey@v2.0.0
        with:
          args: uninstall --force --confirm terragrunt