name: Build

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  terragrunt:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Choco install Terraform
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install terraform

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: pack .\terragrunt\terragrunt.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install -source . -force terragrunt

      - name: Terragrunt & Terraform Version
        run: |
          terragrunt -version
          terraform -version