name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-terragrunt:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: pack .\terragrunt\terragrunt.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -source . -force terragrunt

      - name: Terragrunt
        run: |
          terragrunt -version

      - name: Save Choco package
        uses: actions/upload-artifact@v4
        with:
          name: terragrunt
          path: "${{ github.workspace }}/*.nupkg"
      
      - name: Choco uninstall
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: uninstall --force --confirm terragrunt

  publish-terragrunt:
    runs-on: windows-latest

    needs: build-terragrunt

    steps:
      - uses: actions/checkout@v4

      - name: Restore Choco package
        uses: actions/download-artifact@v4
        with:
          name: terragrunt
          path: ${{ github.workspace }}

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install -source . -force terragrunt

      - name: Terragrunt
        run: |
          terragrunt -version

      - name: Add Choco API Key
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: apikey --key ${{ secrets.CHOCO_API_KEY }} --source https://push.chocolatey.org/

      - name: Publish (noop)
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: push --source https://push.chocolatey.org/