name: Publish

on:
  push:
    branches: [ main ]

jobs:
  build-terragrunt:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Choco install Terraform
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install terraform

      - name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: pack .\terragrunt\terragrunt.nuspec

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install -source . -force terragrunt

      - name: Terragrunt & Terraform Version
        run: |
          terragrunt -version
          terraform -version

      - name: Save Choco package
        uses: actions/upload-artifact@v2
        with:
          name: terragrunt
          path: "${{ github.workspace }}/*.nupkg"

  publish-terragrunt:
    runs-on: windows-latest

    needs: build-terragrunt

    steps:
      - uses: actions/checkout@v2.3.5

      - name: Choco install Terraform
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install terraform

      - name: Restore Choco package
        uses: actions/download-artifact@v2
        with:
          name: terragrunt
          path: ${{ github.workspace }}

      - name: Choco install
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: install -source . -force terragrunt

      - name: Terragrunt & Terraform Version
        run: |
          terragrunt -version
          terraform -version

      - name: Add Choco API Key
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: apikey --key ${{secrets.CHOCO_API_KEY}} --source https://push.chocolatey.org/

      - name: Publish (noop)
        uses: crazy-max/ghaction-chocolatey@v1.6.0
        with:
          args: push